//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWSStat.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.comex.com/Util/ws/SUtiFolioStatWSDL", ConfigurationName="ServiceReference1.SUtiFolioStat_PortType")]
    public interface SUtiFolioStat_PortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultarFoliosStat no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="consultarFoliosStat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PruebaWSStat.ServiceReference1.consultarFoliosStatResponse consultarFoliosStat(PruebaWSStat.ServiceReference1.consultarFoliosStatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="consultarFoliosStat", ReplyAction="*")]
        System.Threading.Tasks.Task<PruebaWSStat.ServiceReference1.consultarFoliosStatResponse> consultarFoliosStatAsync(PruebaWSStat.ServiceReference1.consultarFoliosStatRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DBA_ConsultarStats")]
    public partial class DBA_ConsultarStatsInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DBA_ConsultarStats")]
    public partial class DBA_ConsultarStatsOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stat_folioField;
        
        private string tracking_numberField;
        
        private string appl_cdField;
        
        private string descr_shortField;
        
        private string update_dtField;
        
        private string update_userField;
        
        private string csr_status_cdField;
        
        private string descrField;
        
        private string assigned_userField;
        
        private string open_userField;
        
        private string proj_cdField;
        
        private string tipo_folioField;
        
        private string open_dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string stat_folio {
            get {
                return this.stat_folioField;
            }
            set {
                this.stat_folioField = value;
                this.RaisePropertyChanged("stat_folio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string tracking_number {
            get {
                return this.tracking_numberField;
            }
            set {
                this.tracking_numberField = value;
                this.RaisePropertyChanged("tracking_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string appl_cd {
            get {
                return this.appl_cdField;
            }
            set {
                this.appl_cdField = value;
                this.RaisePropertyChanged("appl_cd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string descr_short {
            get {
                return this.descr_shortField;
            }
            set {
                this.descr_shortField = value;
                this.RaisePropertyChanged("descr_short");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string update_dt {
            get {
                return this.update_dtField;
            }
            set {
                this.update_dtField = value;
                this.RaisePropertyChanged("update_dt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string update_user {
            get {
                return this.update_userField;
            }
            set {
                this.update_userField = value;
                this.RaisePropertyChanged("update_user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string csr_status_cd {
            get {
                return this.csr_status_cdField;
            }
            set {
                this.csr_status_cdField = value;
                this.RaisePropertyChanged("csr_status_cd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
                this.RaisePropertyChanged("descr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string assigned_user {
            get {
                return this.assigned_userField;
            }
            set {
                this.assigned_userField = value;
                this.RaisePropertyChanged("assigned_user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string open_user {
            get {
                return this.open_userField;
            }
            set {
                this.open_userField = value;
                this.RaisePropertyChanged("open_user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string proj_cd {
            get {
                return this.proj_cdField;
            }
            set {
                this.proj_cdField = value;
                this.RaisePropertyChanged("proj_cd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string tipo_folio {
            get {
                return this.tipo_folioField;
            }
            set {
                this.tipo_folioField = value;
                this.RaisePropertyChanged("tipo_folio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string open_date {
            get {
                return this.open_dateField;
            }
            set {
                this.open_dateField = value;
                this.RaisePropertyChanged("open_date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarFoliosStatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DBA_ConsultarStats", Order=0)]
        public PruebaWSStat.ServiceReference1.DBA_ConsultarStatsInput DBA_ConsultarStatsInput;
        
        public consultarFoliosStatRequest() {
        }
        
        public consultarFoliosStatRequest(PruebaWSStat.ServiceReference1.DBA_ConsultarStatsInput DBA_ConsultarStatsInput) {
            this.DBA_ConsultarStatsInput = DBA_ConsultarStatsInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarFoliosStatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DBA_ConsultarStats", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PruebaWSStat.ServiceReference1.DBA_ConsultarStatsOutput[] DBA_ConsultarStatsOutputCollection;
        
        public consultarFoliosStatResponse() {
        }
        
        public consultarFoliosStatResponse(PruebaWSStat.ServiceReference1.DBA_ConsultarStatsOutput[] DBA_ConsultarStatsOutputCollection) {
            this.DBA_ConsultarStatsOutputCollection = DBA_ConsultarStatsOutputCollection;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SUtiFolioStat_PortTypeChannel : PruebaWSStat.ServiceReference1.SUtiFolioStat_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SUtiFolioStat_PortTypeClient : System.ServiceModel.ClientBase<PruebaWSStat.ServiceReference1.SUtiFolioStat_PortType>, PruebaWSStat.ServiceReference1.SUtiFolioStat_PortType {
        
        public SUtiFolioStat_PortTypeClient() {
        }
        
        public SUtiFolioStat_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SUtiFolioStat_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SUtiFolioStat_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SUtiFolioStat_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PruebaWSStat.ServiceReference1.consultarFoliosStatResponse PruebaWSStat.ServiceReference1.SUtiFolioStat_PortType.consultarFoliosStat(PruebaWSStat.ServiceReference1.consultarFoliosStatRequest request) {
            return base.Channel.consultarFoliosStat(request);
        }
        
        public PruebaWSStat.ServiceReference1.DBA_ConsultarStatsOutput[] consultarFoliosStat(PruebaWSStat.ServiceReference1.DBA_ConsultarStatsInput DBA_ConsultarStatsInput) {
            PruebaWSStat.ServiceReference1.consultarFoliosStatRequest inValue = new PruebaWSStat.ServiceReference1.consultarFoliosStatRequest();
            inValue.DBA_ConsultarStatsInput = DBA_ConsultarStatsInput;
            PruebaWSStat.ServiceReference1.consultarFoliosStatResponse retVal = ((PruebaWSStat.ServiceReference1.SUtiFolioStat_PortType)(this)).consultarFoliosStat(inValue);
            return retVal.DBA_ConsultarStatsOutputCollection;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PruebaWSStat.ServiceReference1.consultarFoliosStatResponse> PruebaWSStat.ServiceReference1.SUtiFolioStat_PortType.consultarFoliosStatAsync(PruebaWSStat.ServiceReference1.consultarFoliosStatRequest request) {
            return base.Channel.consultarFoliosStatAsync(request);
        }
        
        public System.Threading.Tasks.Task<PruebaWSStat.ServiceReference1.consultarFoliosStatResponse> consultarFoliosStatAsync(PruebaWSStat.ServiceReference1.DBA_ConsultarStatsInput DBA_ConsultarStatsInput) {
            PruebaWSStat.ServiceReference1.consultarFoliosStatRequest inValue = new PruebaWSStat.ServiceReference1.consultarFoliosStatRequest();
            inValue.DBA_ConsultarStatsInput = DBA_ConsultarStatsInput;
            return ((PruebaWSStat.ServiceReference1.SUtiFolioStat_PortType)(this)).consultarFoliosStatAsync(inValue);
        }
    }
}
